USE [G:\PROJECTS\PROJECTS VS_2015\REALESTATETRANSACTIONMANAGEMENT_WINFRM\REALESTATETRANSACTIONMANAGEMENT_WINFRM\DBMANAGEMENT.MDF]
GO

DECLARE	@return_value Int

EXEC	@return_value = [dbo].[sp_getHouse]
		@_id = NULL

SELECT	@return_value as 'Return Value'

GO
